# Generated by Django 6.0.5 on 2026-08-09 18:03

import apps.quizzes.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0003_quiz_metadata'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Arena',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, default=apps.quizzes.models.generate_arena_code, max_length=8, unique=True)),
                ('topics', models.JSONField(blank=True, default=list)),
                ('question_count', models.PositiveSmallIntegerField(default=10)),
                ('max_players', models.PositiveSmallIntegerField(default=10)),
                ('status', models.CharField(choices=[('waiting', 'Kutilmoqda'), ('started', 'Boshlandi'), ('finished', 'Yakunlandi'), ('cancelled', 'Bekor qilindi')], db_index=True, default='waiting', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_arenas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Arena',
                'verbose_name_plural': 'Arenalar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ArenaParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_owner', models.BooleanField(default=False)),
                ('score', models.PositiveIntegerField(default=0)),
                ('correct_answers', models.PositiveSmallIntegerField(default=0)),
                ('total_time', models.PositiveIntegerField(default=0)),
                ('rank', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('xp_awarded', models.BooleanField(default=False)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('arena', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='quizzes.arena')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arena_participations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Arena ishtirokchisi',
                'verbose_name_plural': 'Arena ishtirokchilari',
                'ordering': ['-score', 'total_time', 'joined_at'],
            },
        ),
        migrations.CreateModel(
            name='ArenaAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_correct', models.BooleanField(default=False)),
                ('response_time', models.PositiveIntegerField(default=0)),
                ('points', models.PositiveIntegerField(default=0)),
                ('answered_at', models.DateTimeField(auto_now_add=True)),
                ('arena', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='quizzes.arena')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='arena_answers', to='quizzes.question')),
                ('selected_option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='arena_answers', to='quizzes.answeroption')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='quizzes.arenaparticipant')),
            ],
            options={
                'verbose_name': 'Arena javobi',
                'verbose_name_plural': 'Arena javoblari',
                'ordering': ['answered_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ArenaQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField()),
                ('arena', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='quizzes.arena')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='arena_questions', to='quizzes.question')),
            ],
            options={
                'verbose_name': 'Arena savoli',
                'verbose_name_plural': 'Arena savollari',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='arenaparticipant',
            constraint=models.UniqueConstraint(fields=('arena', 'user'), name='unique_arena_participant'),
        ),
        migrations.AddConstraint(
            model_name='arenaanswer',
            constraint=models.UniqueConstraint(fields=('participant', 'question'), name='unique_arena_answer'),
        ),
        migrations.AddConstraint(
            model_name='arenaquestion',
            constraint=models.UniqueConstraint(fields=('arena', 'question'), name='unique_arena_question'),
        ),
        migrations.AddConstraint(
            model_name='arenaquestion',
            constraint=models.UniqueConstraint(fields=('arena', 'order'), name='unique_arena_question_order'),
        ),
    ]
