# Generated by Django 6.0.5 on 2026-08-09 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0004_arena_arenaparticipant_arenaanswer_arenaquestion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='arena',
            name='question_duration',
            field=models.PositiveSmallIntegerField(default=20),
        ),
    ]
