# Generated by Django 6.0.5 on 2026-08-09 18:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0005_arena_question_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointtransaction',
            name='arena',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='point_transactions', to='quizzes.arena'),
        ),
    ]
