# Generated by Django 6.0.5 on 2026-05-15 19:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=1, verbose_name='Tartib')),
                ('title', models.CharField(max_length=255, verbose_name='Sarlavha')),
                ('slug', models.SlugField(blank=True, max_length=255)),
                ('duration', models.CharField(max_length=50, verbose_name='Davomiyligi')),
                ('is_free', models.BooleanField(default=False, verbose_name='Bepul')),
                ('video_id', models.CharField(blank=True, max_length=50, verbose_name='YouTube Video ID')),
                ('content', models.TextField(blank=True, verbose_name='Kontent (Markdown)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Dars',
                'verbose_name_plural': 'Darslar',
                'ordering': ['course', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Sarlavha')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('short_description', models.TextField(verbose_name='Qisqa tavsif')),
                ('cover', models.ImageField(upload_to='courses/covers/', verbose_name='Muqova')),
                ('level', models.CharField(choices=[("Boshlang'ich", "Boshlang'ich"), ("O'rta", "O'rta"), ('Yuqori', 'Yuqori')], max_length=20, verbose_name='Daraja')),
                ('price', models.CharField(choices=[('Bepul', 'Bepul'), ('Pullik', 'Pullik')], default='Bepul', max_length=10, verbose_name='Narx')),
                ('duration', models.CharField(max_length=50, verbose_name='Davomiyligi')),
                ('students', models.PositiveIntegerField(default=0, verbose_name="O'quvchilar soni")),
                ('featured', models.BooleanField(default=False, verbose_name='Tanlangan')),
                ('published', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='blog.category', verbose_name='Kategoriya')),
            ],
            options={
                'verbose_name': 'Kurs',
                'verbose_name_plural': 'Kurslar',
                'ordering': ['-created_at'],
            },
        ),
    ]
